### PR TITLE
French translation update 1.11

### PR DESCRIPTION
**Pull request by B-CE**

### CODE REVIEW

**Comment by Erihel** [comment]
Those 2 commits that fix compilation error should be squashed into single commit.

I would also rewrite commit message to something more meaningful. I know colobot git history has a lot of bad commit messages (I wrote some of them :/) but please read https://chris.beams.io/posts/git-commit/

**Comment by B-CE** [comment]
Ok, thanks.
At it was needed it for compilation, it's embedded into all my PR.
(I'll try to do so)

**Comment by Erihel** [comment]
This pull request now shows 97 commits. That can be avoided if you do rebase instead of merge.

**Comment by B-CE** [comment]
Now I think it's managed ! Thank you and my apologies for intermediate inconvenient !
