### ISSUE TITLE
Travis build fails

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#393]
```[  7%] Building CXX object src/CMakeFiles/colobotbase.dir/common/resources/resourcemanager.cpp.o
cd /home/travis/build/colobot/colobot/build/src && /usr/bin/g++   -DTESTS -DTEST_VIRTUAL=virtual -Wall -Wold-style-cast -std=c++0x -Doverride= -DBOOST_NO_SCOPED_ENUMS -DBOOST_NO_CXX11_SCOPED_ENUMS  -I/usr/include/AL -I/home/travis/build/colobot/colobot/src -I/home/travis/build/colobot/colobot/src/.. -I/home/travis/build/colobot/colobot/build/src -isystem /usr/include/SDL -isystem /home/travis/build/colobot/colobot/lib/localename -isystem /home/travis/build/colobot/colobot/lib/clipboard/include    -o CMakeFiles/colobotbase.dir/common/resources/resourcemanager.cpp.o -c /home/travis/build/colobot/colobot/src/common/resources/resourcemanager.cpp
/home/travis/build/colobot/colobot/src/common/resources/resourcemanager.cpp: In static member function ‘static bool CResourceManager::Copy(const string&, const string&)’:
/home/travis/build/colobot/colobot/src/common/resources/resourcemanager.cpp:295:13: error: ‘copy’ is not a member of ‘fs’
/home/travis/build/colobot/colobot/src/common/resources/resourcemanager.cpp:295:13: note: suggested alternatives:
/usr/include/c++/4.6/bits/stl_deque.h:369:5: note:   ‘std::copy’
/usr/include/boost/filesystem/v3/operations.hpp:370:8: note:   ‘boost::filesystem3::copy’
/usr/include/boost/filesystem/v3/operations.hpp:214:10: note:   ‘boost::filesystem3::detail::copy’
/usr/include/c++/4.6/bits/stl_algobase.h:444:5: note:   ‘std::copy’
/usr/include/c++/4.6/bits/stl_deque.h:369:5: note:   ‘std::copy’
/usr/include/c++/4.6/bits/stl_deque.h:369:5: note:   ‘std::copy’
/usr/include/c++/4.6/bits/stl_deque.h:369:5: note:   ‘std::copy’
/usr/include/c++/4.6/bits/stl_deque.h:369:5: note:   ‘std::copy’
make[2]: *** [src/CMakeFiles/colobotbase.dir/common/resources/resourcemanager.cpp.o] Error 1
make[2]: Leaving directory `/home/travis/build/colobot/colobot/build'
make[1]: *** [src/CMakeFiles/colobotbase.dir/all] Error 2
make[1]: Leaving directory `/home/travis/build/colobot/colobot/build'
make: *** [all] Error 2```

**Comment by krzys-h** [comment]
Looks like we have another problem now:
```
[  1%] Building CXX object src/CMakeFiles/colobotbase.dir/app/app.cpp.o
cd /home/travis/build/colobot/colobot/build/src && /usr/bin/g++   -DTESTS -DTEST_VIRTUAL=virtual -Wall -Wold-style-cast -std=c++0x -Doverride= -DBOOST_NO_SCOPED_ENUMS -DBOOST_NO_CXX11_SCOPED_ENUMS  -I/usr/include/AL -I/home/travis/build/colobot/colobot/src -I/home/travis/build/colobot/colobot/src/.. -I/home/travis/build/colobot/colobot/build/src -isystem /usr/include/SDL -isystem /home/travis/build/colobot/colobot/lib/localename -isystem /home/travis/build/colobot/colobot/lib/clipboard/include    -o CMakeFiles/colobotbase.dir/app/app.cpp.o -c /home/travis/build/colobot/colobot/src/app/app.cpp
In file included from /home/travis/build/colobot/colobot/src/app/app.cpp:41:0:
/home/travis/build/colobot/colobot/src/object/objman.h:64:68: error: expected primary-expression before ‘{’ token
In file included from /home/travis/build/colobot/colobot/src/app/app.cpp:41:0:
/home/travis/build/colobot/colobot/src/object/objman.h:66:112: error: expected primary-expression before ‘{’ token
/home/travis/build/colobot/colobot/src/object/objman.h:71:74: error: expected primary-expression before ‘{’ token
/home/travis/build/colobot/colobot/src/object/objman.h:73:101: error: expected primary-expression before ‘{’ token
make[2]: *** [src/CMakeFiles/colobotbase.dir/app/app.cpp.o] Error 1
make[2]: Leaving directory `/home/travis/build/colobot/colobot/build'
make[1]: *** [src/CMakeFiles/colobotbase.dir/all] Error 2
make[1]: Leaving directory `/home/travis/build/colobot/colobot/build'
make: *** [all] Error 2
```
For some reason it's not working on gcc 4.6

**Comment by krzys-h** [comment]
Everything seems to work fine now - https://travis-ci.org/colobot/colobot/jobs/55300754
